### ISSUE TITLE
Activating Caps Lock and Num Lock should not affect the rendering of the Bluetooth indicator

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/wingpanel-indicator-keyboard#112] opened 2021-12-06 13:09 UTC
### What Happened?

When I activate Caps Lock or Num Lock from the keyboard, the icon that normally signals my deactivated Bluetooth in the Wingpanel Bluetooth Indicator briefly flickers white, just as if it were activated.

Also, I have noticed that if I have previously activated Caps Lock or Num Lock this way, additionally activating Num Lock or Caps Lock does not trigger another flare.

### Steps to Reproduce

1. Activate Num Lock or Caps Lock via the keyboard.

### Expected Behavior

The Bluetooth icon does not flicker when I activate Caps Lock or Num Lock via the keyboard.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-07-07 13:21
Closing as duplicate of https://github.com/elementary/wingpanel/issues/106.

**Closed by lenemter** 2023-07-07 13:21 UTC
