### ISSUE TITLE
Indicator is not shown in greeter

### ISSUE THREAD

**Issue by worldofpeace** [elementary/wingpanel-indicator-keyboard#70] opened 2020-07-08 04:55 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
If we look at the sourcecode for wingpanel-indicator-keyboard, the indicator is omitted from a wingpanel in a greeter session seemingly because it caused a "crash" a long time ago https://github.com/elementary/wingpanel-indicator-keyboard/blame/d42e530a541f6a24e01eb0721240c30dd50fe488/src/Indicator.vala#L108.

I really think this would be useful to people in a greeter session, no?
If we agree, I'd be happy to PR removing that code.

**Comment by ryonakano** [comment] 2020-07-10 11:14
I guess this is a duplicate of #5 and elementary/greeter#128.

**Closed by ryonakano** 2020-07-10 11:14 UTC

**Comment by worldofpeace** [comment] 2020-07-10 18:00
I guess I'll just fix it since it's confirmed
