### ISSUE TITLE
Slow keyboard layouts switch [$10]

### ISSUE THREAD

**Issue by d1moncom** [elementary/wingpanel-indicator-keyboard#43] opened 2018-09-26 10:03 UTC
I use a keyboard with two layouts - EN (english) and RU (russian). Switching between layouts tried buttons ALT+SHIFT and CTRL+SHIFT. Switching occurs with a delay of about a second. Because of this, when I switch and start typing, the first letter of word  obtained in a different layout. It is very uncomfortable.

Demo: йййййй йqqqqqq ййййййй йqqqqq ййййййй ййqqqqq ййййййййй ййqqqqqq ййййййй qqqqqqqq ййййййй йqqqqqqq йqqqqqqqqq ййййййййй

**Comment by Ladone** [comment] 2018-10-29 11:55
I have the same problem :c

**Comment by peteruithoven** [comment] 2019-02-11 13:42
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/220

**Comment by peteruithoven** [comment] 2019-02-11 13:42
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/220

**Closed by peteruithoven** 2019-02-11 13:42 UTC
Labels: Bounty, Status: Duplicate

**Comment by jeremypw** [comment] 2019-02-11 14:02
As this is closed, does the bounty need transferring?

**Comment by peteruithoven** [comment] 2019-02-11 20:00
@d1moncom Could you transfer your bounty for elementary/gala#220?

**Comment by Ladone** [comment] 2019-02-14 13:48
My problem was that I confused global variables and pasted code where the loop with windows was initialized.
