### ISSUE TITLE
How to change the color of the indicators in wingpanel?

### ISSUE THREAD

**Issue by kooshkaki** [elementary/wingpanel-indicator-keyboard#63] opened 2019-12-26 05:37 UTC
How to remove keyboard background white color from wingpanel?

https://www.reddit.com/r/elementaryos/comments/ef5cmb/how_to_change_the_color_of_the_indicators_in_the/

**Comment by danrabbit** [comment] 2019-12-30 22:12
Hmm, I can't seem to reproduce this issue. It looks like the keyboard indicator updates with the correct background with the default stylesheet.

OP, are you experiencing this issue with a custom CSS stylesheet?

**Comment by kooshkaki** [comment] 2019-12-31 19:32
Yes I have encountered this issue in a customized theme (gtk.css).

**Comment by danrabbit** [comment] 2020-01-03 06:07
Okay closing this issue as "Out of scope". 3rd party stylesheets are unsupported

**Closed by danrabbit** 2020-01-03 06:07 UTC
Labels: Status: Incomplete
