### ISSUE TITLE
layout indicator is not displayed

### ISSUE THREAD

**Issue by labi-le** [elementary/wingpanel-indicator-keyboard#79] opened 2020-10-30 14:54 UTC

**Comment by michaljenicek** [comment] 2020-11-02 16:41
Hi, I'm having the same issue, on Elementary 5.1.7 Hera when I add another keyboard layout, the keyboard indicator doesn't appear (even though package is installed), I even tried manually building it according to your instructions, but it doesn't appear.

Do you have any ideas what could be the problem?

Thank you.

**Comment by ryonakano** [comment] 2020-11-06 01:53
Closing as a duplicate of #80

**Closed by ryonakano** 2020-11-06 01:53 UTC
